<template lang="html">
  <div class="loading-page" v-if="loading">
    <div class="loadingio-spinner-bean-eater-7x4ie975iwv"><div class="ldio-jb3kv2euomp">
    <div><div></div><div></div><div></div></div><div><div></div><div></div><div></div></div>
    </div></div>
    <h1 id="loading-title" data-text="Chargement…">Chargement…</h1>
  </div>
</template>

<script>
export default {
  data: () => ({
    loading: false
  }),
  methods: {
    start () {
      this.loading = true
    },
    finish () {
      this.loading = false
    }
  }
}
</script>

<style scoped>
.loading-page {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: #000;
  text-align: center;
  padding-top: 200px;
  font-size: 30px;
  font-family: sans-serif;
  z-index: 10;
}
@keyframes ldio-jb3kv2euomp-1 {
    0% { transform: rotate(0deg) }
   50% { transform: rotate(-45deg) }
  100% { transform: rotate(0deg) }
}
@keyframes ldio-jb3kv2euomp-2 {
    0% { transform: rotate(180deg) }
   50% { transform: rotate(225deg) }
  100% { transform: rotate(180deg) }
}
.ldio-jb3kv2euomp > div:nth-child(2) {
  transform: translate(-15px,0);
}
.ldio-jb3kv2euomp > div:nth-child(2) div {
  position: absolute;
  top: 40.8px;
  left: 40.8px;
  width: 122.4px;
  height: 61.2px;
  border-radius: 122.4px 122.4px 0 0;
  background: #fff200;
  animation: ldio-jb3kv2euomp-1 1s linear infinite;
  transform-origin: 61.2px 61.2px
}
.ldio-jb3kv2euomp > div:nth-child(2) div:nth-child(2) {
  animation: ldio-jb3kv2euomp-2 1s linear infinite
}
.ldio-jb3kv2euomp > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}@keyframes ldio-jb3kv2euomp-3 {
    0% { transform: translate(193.8px,0); opacity: 0 }
   20% { opacity: 1 }
  100% { transform: translate(71.4px,0); opacity: 1 }
}
.ldio-jb3kv2euomp > div:nth-child(1) {
  display: block;
}
.ldio-jb3kv2euomp > div:nth-child(1) div {
  position: absolute;
  top: 93.84px;
  left: -8.16px;
  width: 16.32px;
  height: 16.32px;
  border-radius: 50%;
  background: #fbff00;
  animation: ldio-jb3kv2euomp-3 1s linear infinite
}
.ldio-jb3kv2euomp > div:nth-child(1) div:nth-child(1) { animation-delay: -0.67s }
.ldio-jb3kv2euomp > div:nth-child(1) div:nth-child(2) { animation-delay: -0.33s }
.ldio-jb3kv2euomp > div:nth-child(1) div:nth-child(3) { animation-delay: 0s }
.loadingio-spinner-bean-eater-7x4ie975iwv {
  width: 204px;
  height: 204px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-jb3kv2euomp {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-jb3kv2euomp div { box-sizing: content-box; }
/* generated by https://loading.io/ */

#loading-title {
    position: relative;
    color: rgba(255, 255, 255, 0.3);
    font-size: 2em
}
#loading-title:before {
    content: attr(data-text);
    position: absolute;
    overflow: hidden;
    max-width: 8em;
    white-space: nowrap;
    color: #fff;
    animation: loading 3s linear;
}
@keyframes loading {
    0% {
        max-width: 0;
    }
}
</style>